#!/bin/bash

set -euo pipefail

run () {
    echo "+" "$@" 1>&2
    "$@"
}

EXPECTED_ARGS=0
E_BADARGS=65

usage () {
    echo "Usage: $0"
    echo "  Must be run from the directory above this checkout"
}

if [ $# -ne $EXPECTED_ARGS ]; then
    usage
    exit $E_BADARGS
fi

if [[ ! -e ansible-harness ]]; then
    echo "Must run from directory above ansible-harness" 1>&2
    usage
    exit 1
fi

copy_example () {
    if [[ ! -e $1 ]]; then
        run cp -r "ansible-harness/$1" "$1"
    fi
}

make_symlink () {
    if [[ ! -e $1 ]]; then
        run ln -s "ansible-harness/$1" "$1"
    fi
}

make_symlink .gitignore
make_symlink amifind.sh
make_symlink Rakefile
make_symlink Gemfile
make_symlink install-packer-serverspec-plugin.sh
make_symlink packer
copy_example serverspec
copy_example roles
copy_example requirements.yml
copy_example playbook.yml
copy_example bootstrap.sh
