#!/bin/bash

set -euo pipefail

run () {
    echo "+" "$@" 1>&2
    "$@"
}

usage () {
    cat <<EOF
Usage: $0 <create|configure|validate|destroy|full-cycle> [provider]

  Runner script for all the stages necessary to test an Ansible playbook.

    create:     spins up a VM using [provider] (default virtualbox)
    update:     refresh the local Ansible roles from ./requirements.yml
    configure:  runs ansible in local mode on the VM using ./playbook.yml
    validate:   runs serverspec tests in ./serverspec against the VM
    destroy:    destroys the VM
    full-cycle: destroy, create, update, configure, validate, and destroy

  Behind the scenes this is a vagrant box, so you should be able to log in using
  "vagrant ssh" if there is an issue.

  Currently, the only supported provider is virtualbox.

EOF
}

if [[ $# -lt 1 ]]; then
    usage
    exit 1
fi

PROVIDER=${2:-virtualbox}
COMMAND=$1

# TODO: Dynamically discover these, and pass them to vagrant in a better way.
# See:
# https://stackoverflow.com/questions/14124234/how-to-pass-parameter-on-vagrant-up-and-have-it-in-the-scope-of-vagrantfile#14124316
export ANSIBLE_HARNESS_AMI="${ANSIBLE_HARNESS_AMI:-ami-d651b8ac}"
export ANSIBLE_HARNESS_SUBNET_ID="${ANSIBLE_HARNESS_SUBNET_ID:-subnet-419ca21b}"
export ANSIBLE_HARNESS_SECURITY_GROUP="${ANSIBLE_HARNESS_SECURITY_GROUP:-sg-6aa38c19}"

create () {
    case $PROVIDER in
        virtualbox)
            ;;
        aws)
            if ! vagrant box list | grep vagrant-aws-dummy-placeholder > /dev/null; then
                run vagrant box add vagrant-aws-dummy-placeholder https://github.com/mitchellh/vagrant-aws/raw/master/dummy.box
            fi
            if ! aws ec2 describe-key-pairs --query "KeyPairs[*].KeyName" --output text | grep ansible-harness-test-key > /dev/null; then
                run aws ec2 import-key-pair --key-name ansible-harness-test-key --public-key-material file://./.ssh-test-key/id_rsa.pub
            fi
            ;;
        *)
            echo "Unrecognized provider: $PROVIDER"
            usage
            exit 1
            ;;
    esac
    run vagrant up --provider "$PROVIDER" --no-provision
}

update () {
    run rm -rf roles/*
    run ansible-galaxy -p roles -r requirements.yml install -v -f
}

configure () {
    run vagrant provision --provision-with ansible_local
}

validate () {
    run vagrant provision --provision-with serverspec
}

destroy () {
    if vagrant status | grep "not created" > /dev/null; then
        echo "Vagrant box not created, not running destroy" 1>&2
    else
        run vagrant destroy -f
    fi
}

full-cycle () {
    run destroy
    run create
    run update
    run configure
    run validate
    run destroy
}

install_plugin () {
    if ! vagrant plugin list | grep "$1" > /dev/null; then
        run vagrant plugin install "$1"
    fi
}

# https://github.com/vvchik/vagrant-serverspec
install_plugin vagrant-serverspec
# https://github.com/mitchellh/vagrant-aws
install_plugin vagrant-aws

case $COMMAND in
    create)
        create
        ;;
    update)
        update
        ;;
    configure)
        configure
        ;;
    validate)
        validate
        ;;
    destroy)
        destroy
        ;;
    full-cycle)
        full-cycle
        ;;
    *)
        echo "Unrecognized command: $COMMAND"
        usage
        exit 1
        ;;
esac
